name: Test Current Version

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install current development version of package
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Checkout examples repo
        uses: actions/checkout@v4
        with:
          repository: tofupilot/examples
          path: examples

      - name: Run example scripts
        env:
          TOFUPILOT_API_KEY: ${{ secrets.TOFUPILOT_API_KEY }}
        run: |
          cd examples
          pip install -r requirements.txt
          find . -type f -name 'main.py' -not -path '*/venv/*' -print0 | while IFS= read -r -d '' file; do
            echo "Running $file"
            python "$file"
          done
